### ISSUE TITLE
Unit Test coverage

### ISSUE THREAD

**Issue by rashidsaf** [Medology/gherkin-cs-fixer#11]
## Description
There is no Unit test coverage for this repo

# Acceptance Criteria
- [ ] Add tests to cover all the step definitions
- [ ] Unit test should cover all supported formatting behaviors (Remove extra lines, aligning etc)
- [ ] Edge cases

**Comment by Chekote** [comment]
We will not do this because we are moving away from Gherkin tests and having Automated QA take it over with Selenium and Cucumber
