### ISSUE TITLE
PyString's content indentation is not fixed

### ISSUE THREAD

**Issue by Chekote** [Medology/gherkin-cs-fixer#12]
## Given the following feature file:

```gherkin
  Background:
    Given something
 And something else with:
   """
  some text

some more text
"""
```

## When I run the fixer, I should see:

```gherkin
  Background:
    Given something
      And something else with:
          """
          some text

          some more text
          """
```

## But I see:

```gherkin
  Background:
    Given something
      And something else with:
          """
  some text

some more text
          """
```

**Comment by rashidsaf** [comment]
@This is intended. Because Pystring content is very strict even `space` would cause test to fail. So the script will only fix the starting and ending markups

**Comment by BKorenek** [comment]
@Chekote @rashidsaf The comments appear to be a little wonky as well. In some scenarios it lines em up, some scenarios it pushes em to the far left side of the file. 

features/api/testing/reset.feature lines 9 and 23 for example.

**Comment by rashidsaf** [comment]
@BKorenek This is because line 23 is recognized as a commented line inside table, others as a step comment. This could be fixed

**Comment by rashidsaf** [comment]
Scored with @johnnie502 and @DevanTarunKumar

**Comment by MeganPartida** [comment]
nothing for me to qA on this - updating to **approval**
