### ISSUE TITLE
Empty lines in PyStrings are prefixed with spaces

### ISSUE THREAD

**Issue by Chekote** [Medology/gherkin-cs-fixer#15]
## Method
Run gherkin-cs-fixer on the following scenario
```gherkin
Given some condition
    """
    something

    something else
    """
When I do something
Then I expect something
```

## Expected Behavior
The empty line in the PyString should not be modified

## Actual Behavior
4 spaces are added to the beginning of the empty line

## Notes
See this PR as an example: https://github.com/Medology/stdcheck.com/pull/9064/files#diff-10b05527d0e4a8be92583c81b3f3a475R134

**Comment by rashidsaf** [comment]
@Chekote  This behavior doesn't affect the content inside the pystrings. As mentioned here http://behat.org/en/latest/user_guide/writing_scenarios.html#pystrings :

`Indentation of the opening """ is not important, although common practice is two spaces in from the enclosing step. The indentation inside the triple quotes, however, is significant. Each line of the string passed to the step definition’s callback will be de-indented according to the opening """. Indentation beyond the column of the opening """ will therefore be preserved.`

**Comment by aserv92** [comment]
Scored this issue with @smijo149 and @DevanTarunKumar

**Comment by aserv92** [comment]
## QA Information

This is used only by the dev team and doesn't go into production.

**Comment by MeganPartida** [comment]
## QA
- nothing for QA to verify
- updating to **deploy & test**

**Comment by aserv92** [comment]
## QA Information

This second PR is to setup stdcheck to use the new image on dev. This change should not affect production
Nothing to test here.

**Comment by MeganPartida** [comment]
## QA - Local - https://github.com/Medology/stdcheck.com/pull/9270
- Discussed with Andrew and there's nothing for me to test on this pr
- updating to **deploy & test**

**Comment by MeganPartida** [comment]
## QA - Prod
- does not affect prod so nothing for me to do
- updating to **deploy & test**

**Comment by Chekote** [comment]
Verified that this is working by adding blank lines to a pynode, committing, and confirming they were not removed.
