### ISSUE TITLE
Multibyte Strings are not handled correctly

### ISSUE THREAD

**Issue by Chekote** [Medology/gherkin-cs-fixer#25]
## Scenario
Given the following file contents:

```gherkin
    Examples:
        | keyword  |
        | Ègg, Ýup |
        | ègg, ýup |
        | èGG, ýUP |
```

When I run the fixer

## Expected Behavior
Then the file should not be changed

## Actual Behavior
Then the file is changed as follows:

```gherkin
    Examples:
        | keyword    |
        | Ègg, Ýup |
        | ègg, ýup |
        | èGG, ýUP |
```

**Comment by johnnie502** [comment]
### QA Note
This change is made to an internal Code Styling tool which is command line based, there's no local or production QA is required. Please move it to Test & Deploy column.

**Comment by Chekote** [comment]
It does not have any impact on production because it is a local testing tool. But it can still impact developer productivity. If someone breaks a developer tool and prevents all the developers from working as a result, that's a big problem. So I would disagree that it doesn't require QA.

**Comment by splinfer** [comment]
## QA - Local

- Verified with @rashidsaf just to make sure on how and what to test
- Add and modify one gherkin file to test the fix on column adjustment, works as described.

Moving to **Deploy&Test**

**Comment by fiyyazp** [comment]
will merge today

**Comment by johnnie502** [comment]
Scored with @jose-ochoa  and @fortoulrodolfo

**Comment by fortoulrodolfo** [comment]
## QA - Local for PR #9979  - https://github.com/Medology/stdcheck.com/pull/9979

- Just updated the Fixer version. Tested locally and it's working as expected. 
- Moving to **Deploy&Test**

**Comment by BKorenek** [comment]
Sanity checked prod already style changer is only thing updated for tests. Moving to Approval. #9999

**Comment by fiyyazp** [comment]
will be submitting a new PR for this today

**Comment by Chekote** [comment]
Will deploy and test today if pre-prod QA passes.

**Comment by johnnie502** [comment]
* Going to merge the bug fix once pass QA
* Create a new PR on STDcheck to update the gherkin-cs-fixer version

**Comment by BKorenek** [comment]
Unable to test Gherkin CS Fixer, moving to deploy and test. https://github.com/Medology/stdcheck.com/issues/10021

**Comment by johnnie502** [comment]
* PR is merged for `ghker-cs-fixer` repo to fix the mb_string extension problem https://github.com/Medology/gherkin-cs-fixer/pull/28
* A new PR is created on STDcheck to bump the cs-fixer version https://github.com/Medology/stdcheck.com/pull/10036

**Comment by BKorenek** [comment]
Awaiting review.

**Comment by johnnie502** [comment]
* https://github.com/Medology/stdcheck.com/pull/10036 Passed review, will be waiting for code review feedback

**Comment by johnnie502** [comment]
* Waiting for QA Medology/stdcheck.com#10036

**Comment by johnnie502** [comment]
* Going to pair up with Julio to QA this issue

**Comment by juliohl** [comment]
### QA - Local ([#10036](https://github.com/Medology/stdcheck.com/pull/10036))
Checked with @johnnie502 along with other issues, this has not much that I can test since it is a change in style changer that only updates tests, a Sanity was run with success, also this behat was run to double-check:

docker/lib/images.sh

**Comment by johnnie502** [comment]
* Merged this morning, going to do a test using the new image today

**Comment by johnnie502** [comment]
* Tested everything works as expected

**Comment by juliohl** [comment]
> ### QA - Local ([#10036](https://github.com/Medology/stdcheck.com/pull/10036))
> Checked with @johnnie502 along with other issues, this has not much that I can test since it is a change in style changer that only updates tests, a Sanity was run with success, also this behat was run to double-check:
> 
> features/web/manage/patients/searchOrders.feature
> 
> Moving to Deploy & Test

Done a sanity in prod, all is working OK. Moving to Approval.

**Comment by Chekote** [comment]
The problem does not seem to be fixed. I just checked out STDcheck master (dce6f8a3093b17939cabb476c30031fa403babad), and made the following change:

```pbcopy
diff --git a/features/web/public/navigation.feature b/features/web/public/navigation.feature
index 5d9326372..025dae3a3 100644
--- a/features/web/public/navigation.feature
+++ b/features/web/public/navigation.feature
@@ -12,7 +12,7 @@ Feature: Navigation bar
     Examples:
         | Path                                        | Should_see                    |
         | /                                           | Know Your Status. Get Tested. |
-        | /how-std-testing-works.php                  | How to Get Tested for STDs    |
+        | /höw-std-testing-works.php                  | How to Get Tested for STDs    |
         | /my-account.php#/stdcheck.com/login         | Account Login                 |
         | /my-account.php#/stdcheck.com/resetPassword | Enter the email address       |
```

When I committed the change, the gherking-cs-fixer modified the line so that one of the spaces were removed, causing it to no longer align with the rest of the table:

```patch
diff --git a/features/web/public/navigation.feature b/features/web/public/navigation.feature
index 5d9326372..d300647f2 100644
--- a/features/web/public/navigation.feature
+++ b/features/web/public/navigation.feature
@@ -12,7 +12,7 @@ Feature: Navigation bar
     Examples:
         | Path                                        | Should_see                    |
         | /                                           | Know Your Status. Get Tested. |
-        | /how-std-testing-works.php                  | How to Get Tested for STDs    |
+        | /höw-std-testing-works.php                 | How to Get Tested for STDs    |
         | /my-account.php#/stdcheck.com/login         | Account Login                 |
         | /my-account.php#/stdcheck.com/resetPassword | Enter the email address       |
```

**Comment by Chekote** [comment]
Please let me know if STDcheck is not using the fixed version yet. But I assumed it was since I saw a new version of the gherkin-cs-fixer image being pulled recently.

**Comment by johnnie502** [comment]
@Chekote STDcheck is using the fixed version. Unfortunately the issue you found is a different one, I've fixed the multibyte problem in the TableNode header, this one is in the body.

**Comment by johnnie502** [comment]
* Going to create a new PR in `gherkin-cs-fixer` to fix multibyte problem in the TableNode body

**Comment by johnnie502** [comment]
* #29 is ready for local QA, will assist @juliohl to do that

**Comment by johnnie502** [comment]
* #29 waiting for local QA

**Comment by juliohl** [comment]
### QA Local (#29)
Since this is the tool to format behat tests, and the chances are related only to that scope there is no much to test from QA at least in Local. Paired with @johnnie502 and we will test this in prod, moving to **D&T**

**Comment by juliohl** [comment]
### QA Local (#[10139](https://github.com/Medology/stdcheck.com/pull/10139))
Ran behat tests and all is working as expected, moving to **D&T**.

**Comment by juliohl** [comment]
### QA Local (#[10139](https://github.com/Medology/stdcheck.com/pull/10139))
Executed a Sanity. Since this is about behat tests, there's nothing more from QA to verify, moving to Approval.
