### ISSUE TITLE
Workdir should not contain gherkin-cs-fixer

### ISSUE THREAD

**Issue by Chekote** [Medology/gherkin-cs-fixer#7]
## Problem
The working dir should be where the user can mount their project for gherkin-cs-fixer to fix. But the working dir is where gherkin-cs-fixer itself resides. If a user mounts their source files into the working dir, then gherkin-cs-fixer is unavailable.

## Suggestion
Put the working dir back to `/workdir`. This will allow the user of the Docker image to mount their source files to `/workdir` without overwriting gherkin-cs-fixer and will prevent them from having to change the working dir. Since the entry point is fully qualified, the `/project` working dir should not be required.

**Comment by rashidsaf** [comment]
Scored with @jose-ochoa and @smijo149

**Comment by healthlabs-qa** [comment]
## QA - Local
Nothing to QA moving to deploy and test

QA https://github.com/Medology/stdcheck.com/issues/9054 - JM

**Comment by BKorenek** [comment]
nothing to QA moving to approval 
https://github.com/Medology/stdcheck.com/issues/9089

**Comment by Chekote** [comment]
Moving back to in-progress because the working directory is not `/workdir` as specified in the issue. The image has been updated so that the working directory is no longer `/project`, but neither the gherkin cs-fixer or STDcheck's projects scripts have been updated to use the standard `/workdir` working directory:

### Gherkin CS Fixer:

```shell
#!/bin/bash +x

set -eu

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

. "${ROOT}"/bin/lib/tty.sh
. "${ROOT}"/docker/lib/images.sh

if [[ `uname` == 'Linux' ]]; then
   USER_ARG="-e LOCAL_USER_ID=`id -u`"
fi

docker run \
    -i${TTY} \
    --rm \
    ${USER_ARG} \
    -v "$(pwd)":/app \
    -v ~/.composer:/home/user/.composer \
    -w /app \
	${PHP_IMAGE} php "$@"
```

### STDcheck:

```shell
#!/usr/bin/env bash

set -eu

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

. "$ROOT"/docker/lib/docker_host_user_id.sh
. "$ROOT"/bin/lib/tty.sh
. "$ROOT"/docker/lib/images.sh

docker run \
    -e LOCAL_USER_ID=$DOCKER_HOST_USER_ID \
    -i${TTY} \
    --rm \
    -v $(pwd):/var/www \
    -w /var/www \
    ${GHERKIN_CS_FIXER_IMAGE} "$@"
```

**Comment by MeganPartida** [comment]
## QA - Local
- Discussed with Rashid and both https://github.com/Medology/stdcheck.com/pull/9123 and https://github.com/Medology/gherkin-cs-fixer/pull/16 are related to automated testing so there's nothing for me to do
- updating to **deploy & test**

**Comment by MeganPartida** [comment]
## QA - Prod
- nothing for me to test on this issue, moving to **approval**
