### ISSUE TITLE
Multiline Text Support

### ISSUE THREAD

**Issue by rashidsaf** [Medology/gherkin-cs-fixer#9]
## Problem:
[The script doesn't recognize multiple line text blocks like :

    """
    Email Title
 
    Email Body
    """
And see the empty lines inside the text as unnecessary and removes.

## Requirement

Add multiline text block support

**Comment by MeganPartida** [comment]
## QA - Local
- no testing done
- discussed with Rashid, and now moving to **deploy & test**

**Comment by MeganPartida** [comment]
- same as before, no QA. ready for **approval**
